# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

pr:
  branches:
    include: [main]

pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
          npm install
          npm run build
      displayName: 'npm install and build'

    - script: npm run prettier
      displayName: 'npm prettier'

    - script: npm run lint
      displayName: 'npm lint'

    - script: npm test
      displayName: 'npm test'

    - script: npm run build
      displayName: 'npm run build'
